/**
 * Types for @remotion/mixpeek integration
 */

import type {Caption} from '@remotion/captions';

/**
 * Configuration options for the Mixpeek client
 */
export interface MixpeekConfig {
  	/**
  	 * Your Mixpeek API key
  	 * Get one at https://dash.mixpeek.com
  	 */
	apiKey: string;
  	/**
  	 * Optional namespace for multi-tenant isolation
  	 */
	namespace?: string;
  	/**
  	 * Optional base URL for custom API endpoints
  	 */
	baseUrl?: string;
  	/**
  	 * Optional request timeout in milliseconds
  	 * @default 30000
  	 */
	timeout?: number;
}

/**
 * A segment from Mixpeek's video analysis
 */
export interface MixpeekVideoSegment {
  	/**
  	 * Start time of the segment in seconds
  	 */
	startTime: number;
  	/**
  	 * End time of the segment in seconds
  	 */
	endTime: number;
  	/**
  	 * Transcribed text for this segment (if audio/speech)
  	 */
	text?: string;
  	/**
  	 * Scene description generated by visual analysis
  	 */
	sceneDescription?: string;
  	/**
  	 * Detected objects in this segment
  	 */
	detectedObjects?: string[];
  	/**
  	 * Detected faces/entities
  	 */
	entities?: MixpeekEntity[];
  	/**
  	 * Confidence score (0-1)
  	 */
	confidence?: number;
  	/**
  	 * Visual embedding for this segment
  	 */
	embedding?: number[];
  	/**
  	 * Additional metadata
  	 */
	metadata?: Record<string, unknown>;
}

/**
 * An entity detected by Mixpeek
 */
export interface MixpeekEntity {
  	/**
  	 * Entity type (e.g., 'person', 'speaker', 'object')
  	 */
	type: string;
  	/**
  	 * Entity label or name
  	 */
	label: string;
  	/**
  	 * Bounding box coordinates [x, y, width, height] as percentages
  	 */
	boundingBox?: [number, number, number, number];
  	/**
  	 * Confidence score (0-1)
  	 */
	confidence?: number;
}

/**
 * Video analysis result from Mixpeek
 */
export interface MixpeekVideoAnalysis {
  	/**
  	 * Unique identifier for this analysis
  	 */
	id: string;
  	/**
  	 * Original video URL or path
  	 */
	sourceUrl: string;
  	/**
  	 * Duration of the video in seconds
  	 */
	duration: number;
  	/**
  	 * Frames per second of the video
  	 */
	fps?: number;
  	/**
  	 * All analyzed segments
  	 */
	segments: MixpeekVideoSegment[];
  	/**
  	 * Full transcript if available
  	 */
	transcript?: string;
  	/**
  	 * Overall video summary
  	 */
	summary?: string;
  	/**
  	 * Tags/labels for the entire video
  	 */
	tags?: string[];
  	/**
  	 * When the analysis was created
  	 */
	createdAt: string;
}

/**
 * Search result from Mixpeek
 */
export interface MixpeekSearchResult {
  	/**
  	 * Unique identifier
  	 */
	id: string;
  	/**
  	 * Relevance score (0-1)
  	 */
	score: number;
  	/**
  	 * The matching segment
  	 */
	segment: MixpeekVideoSegment;
  	/**
  	 * Source document/video information
  	 */
	source: {
  		/**
  		 * Video/document ID
  		 */
  		id: string;
  		/**
  		 * Original URL
  		 */
  		url?: string;
  		/**
  		 * Title or name
  		 */
  		title?: string;
  };
  	/**
  	 * Highlighted text matches
  	 */
	highlights?: string[];
}

/**
 * Options for converting Mixpeek analysis to captions
 */
export interface MixpeekToCaptionsOptions {
  	/**
  	 * Maximum caption duration in seconds
  	 * @default 5
  	 */
	maxDuration?: number;
  	/**
  	 * Minimum caption duration in seconds
  	 * @default 0.5
  	 */
	minDuration?: number;
  	/**
  	 * Whether to include scene descriptions as captions
  	 * @default false
  	 */
	includeSceneDescriptions?: boolean;
  	/**
  	 * Whether to include detected objects as captions
  	 * @default false
  	 */
	includeDetectedObjects?: boolean;
  	/**
  	 * Custom caption formatter
  	 */
	formatter?: (segment: Mixpee/**
   * Types for @remotion/mixpeek integration
   */

  import type {Caption} from '@remotion/captions';

/**
   * Configuration options for the Mixpeek client
   */
export interface MixpeekConfig {
  	/**
  	 * Your Mixpeek API key
  	 * Get one at https://dash.mixpeek.com
  	 */
  
