export const GCP_REGIONS = [
	'asia-east1',
	'asia-east2',
	'asia-northeast1',
	'asia-northeast2',
	'asia-northeast3',
	'asia-south1',
	'asia-south2',
	'asia-southeast1',
	'asia-southeast2',
	'australia-southeast1',
	'australia-southeast2',
	'europe-central2',
	'europe-north1',
	'europe-southwest1',
	'europe-west1',
	'europe-west2',
	'europe-west3',
	'europe-west4',
	'europe-west6',
	'europe-west8',
	'europe-west9',
	'me-west1',
	'northamerica-northeast1',
	'northamerica-northeast2',
	'southamerica-east1',
	'southamerica-west1',
	'us-central1',
	'us-east1',
	'us-east4',
	'us-east5',
	'us-south1',
	'us-west1',
	'us-west2',
	'us-west3',
	'us-west4',
] as const;

export const GCP_REGION_SHORTHAND: {[key in GcpRegion]: string} = {
	'us-east5': 'ul.a',
	'asia-east1': 'de.a',
	'asia-east2': 'df.a',
	'asia-northeast1': 'an.a',
	'asia-northeast2': 'dt.a',
	'asia-northeast3': 'du.a',
	'asia-south1': 'el.a',
	'asia-south2': 'em.a',
	'asia-southeast1': 'as.a',
	'asia-southeast2': 'et.a',
	'australia-southeast1': 'ts.a',
	'australia-southeast2': 'km.a',
	'europe-central2': 'lm.a',
	'europe-north1': 'lz.a',
	'europe-southwest1': 'no.a',
	'europe-west1': 'ew.a',
	'europe-west2': 'nw.a',
	'europe-west3': 'ey.a',
	'europe-west4': 'ez.a',
	'europe-west6': 'oa.a',
	'europe-west8': 'oc.a',
	'europe-west9': 'od.a',
	'me-west1': 'zf.a',
	'northamerica-northeast1': 'nn.a',
	'northamerica-northeast2': 'pd.a',
	'southamerica-east1': 'rj.a',
	'southamerica-west1': 'tl.a',
	'us-central1': 'uc.a',
	'us-east1': 'ue.a',
	'us-east4': 'uk.a',
	'us-west1': 'uw.a',
	'us-south1': 'vp.a',
	'us-west2': 'wl.a',
	'us-west4': 'wn.a',
	'us-west3': 'wm.a',
};

export type GcpRegion = typeof GCP_REGIONS[number];
