/*
	This file will give you autocompletions for staticFile().
	Enable autocompletion by adding "autocomplete.d.ts" to the "include" array in "tsconfig.json".
	This file is auto-generated - do not edit this file!
	You may add it to your `.gitignore`.
*/

declare global {
  interface RemotionStaticPaths {
    ["22khz.wav"]: unknown;
    ["balloons.json"]: unknown;
    ["bangers.woff2"]: unknown;
    ["corrupted.mp4"]: unknown;
    ["framer.webm"]: unknown;
    ["framermp4withoutfileextension"]: unknown;
    ["giphy.gif"]: unknown;
    ["music.mp3"]: unknown;
    ["nested/logö.png"]: unknown;
    ["nested/mp4.png"]: unknown;
    ["reverse-loader.json"]: unknown;
  } 
}  
export {}
