
/*
	This file will give you autocompletions for staticFile().
	Enable autocompletion by adding "autocomplete.d.ts" to the "include" array in "tsconfig.json".
	This file is auto-generated - do not edit this file!
	You may add it to your `.gitignore`.
*/

declare global {
  interface RemotionStaticPaths {
		[" 🔽 Suggestions [may be incomplete]"]: unknown;
    ["22khz.wav"]: unknown;
    ["Both.mp4"]: unknown;
    ["balloons.json"]: unknown;
    ["corrupted.mp4"]: unknown;
    ["dddd.mp3"]: unknown;
    ["framer.webm"]: unknown;
    ["framermp4withoutfileextension"]: unknown;
    ["giphy.gif"]: unknown;
    ["hundred"]: unknown;
    ["nested"]: unknown;
    ["reverse-loader.json"]: unknown;
  } 
}  
export {}
