set -e

clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
clear && bunx remotion render empty --concurrency=16 --frames=0-20 --log=verbose
