import {existsSync, mkdirSync, writeFileSync} from 'fs';
import path from 'path';
import type {StaticFile} from './get-files-in-public-folder';

export const writeFilesDefinitionFile = (
	files: StaticFile[],
	remotionRoot: string
) => {
	const content = `
/*
	This file will give you autocompletions for staticFile().
	Enable autocompletion by adding "autocomplete.d.ts" to the "include" array in "tsconfig.json".
	This file is auto-generated - do not edit this file!
	You may add it to your \`.gitignore\`.
*/

declare global {
  interface RemotionStaticPaths {
${files
	.map((f) => {
		// TODO: What if file contains '"'?
		return `    ["${f.path}"]: unknown;`;
	})
	.join('\n')}
  } 
}  
export {}
`.trimStart();

	const folder = path.join(remotionRoot);

	if (!existsSync(folder)) {
		mkdirSync(folder);
	}

	// TODO: Create folder if exists
	writeFileSync(path.join(folder, 'autocomplete.d.ts'), content);
};
