export const incompatibleFonts = [
  "Linefont",
  "Material Icons Outlined",
  "Material Icons Round",
  "Material Icons Sharp",
  "Material Icons Two Tone",
  "Material Symbols",
  "Material Icons",
  "Material Symbols Rounded",
  "Material Symbols Outlined",
  "Material Symbols Sharp",
  "Playwrite AR",
  "Playwrite AR Guides",
  "Playwrite AT",
  "Playwrite AT Guides",
  "Playwrite AU NSW Guides",
  "Playwrite AU NSW",
  "Playwrite AU QLD Guides",
  "Playwrite AU QLD",
  "Playwrite AU SA Guides",
  "Playwrite AU SA",
  "Playwrite AU TAS",
  "Playwrite AU TAS Guides",
  "Playwrite AU VIC",
  "Playwrite AU VIC Guides",
  "Playwrite BE WAL Guides",
  "Playwrite BE VLG Guides",
  "Playwrite BE WAL",
  "Playwrite BE VLG",
  "Playwrite BR",
  "Playwrite BR Guides",
  "Playwrite CA",
  "Playwrite CA Guides",
  "Playwrite CL",
  "Playwrite CO Guides",
  "Playwrite CO",
  "Playwrite CU",
  "Playwrite CL Guides",
  "Playwrite CU Guides",
  "Playwrite CZ",
  "Playwrite CZ Guides",
  "Playwrite DE Grund",
  "Playwrite DE Grund Guides",
  "Playwrite DE SAS",
  "Playwrite DE LA Guides",
  "Playwrite DE LA",
  "Playwrite DE SAS Guides",
  "Playwrite DE VA",
  "Playwrite DE VA Guides",
  "Playwrite DK Loopet Guides",
  "Playwrite DK Loopet",
  "Playwrite DK Uloopet",
  "Playwrite DK Uloopet Guides",
  "Playwrite ES",
  "Playwrite ES Deco",
  "Playwrite ES Deco Guides",
  "Playwrite ES Guides",
  "Playwrite FR Moderne Guides",
  "Playwrite FR Moderne",
  "Playwrite GB J Guides",
  "Playwrite FR Trad Guides",
  "Playwrite FR Trad",
  "Playwrite GB J",
  "Playwrite GB S",
  "Playwrite GB S Guides",
  "Playwrite HR",
  "Playwrite HR Guides",
  "Playwrite HU Guides",
  "Playwrite HR Lijeva Guides",
  "Playwrite HR Lijeva",
  "Playwrite HU",
  "Playwrite ID",
  "Playwrite ID Guides",
  "Playwrite IE",
  "Playwrite IE Guides",
  "Playwrite IN",
  "Playwrite IS",
  "Playwrite IN Guides",
  "Playwrite IS Guides",
  "Playwrite IT Moderna",
  "Playwrite IT Moderna Guides",
  "Playwrite IT Trad",
  "Playwrite MX Guides",
  "Playwrite NL",
  "Playwrite NG Modern Guides",
  "Playwrite MX",
  "Playwrite IT Trad Guides",
  "Playwrite NG Modern",
  "Playwrite NL Guides",
  "Playwrite NO",
  "Playwrite NO Guides",
  "Playwrite PL Guides",
  "Playwrite NZ Guides",
  "Playwrite PL",
  "Playwrite PE Guides",
  "Playwrite PE",
  "Playwrite NZ",
  "Playwrite PT",
  "Playwrite PT Guides",
  "Playwrite RO",
  "Playwrite SK",
  "Playwrite TZ Guides",
  "Playwrite RO Guides",
  "Playwrite TZ",
  "Playwrite SK Guides",
  "Playwrite US Modern Guides",
  "Playwrite US Trad",
  "Playwrite VN",
  "Playwrite US Modern",
  "Playwrite ZA",
  "Playwrite ZA Guides",
  "Playwrite US Trad Guides",
  "Playwrite VN Guides",
  "Wavefont"
];