export const incompatibleFonts = [
  "Linefont",
  "Material Icons",
  "Material Icons Outlined",
  "Material Icons Two Tone",
  "Material Icons Sharp",
  "Material Symbols Outlined",
  "Material Icons Round",
  "Material Symbols",
  "Material Symbols Rounded",
  "Material Symbols Sharp",
  "Playwrite AR Guides",
  "Playwrite AR",
  "Playwrite AT Guides",
  "Playwrite AU NSW",
  "Playwrite AT",
  "Playwrite AU NSW Guides",
  "Playwrite AU QLD Guides",
  "Playwrite AU QLD",
  "Playwrite AU SA Guides",
  "Playwrite AU SA",
  "Playwrite AU TAS",
  "Playwrite AU VIC",
  "Playwrite AU TAS Guides",
  "Playwrite AU VIC Guides",
  "Playwrite BE VLG Guides",
  "Playwrite BE WAL",
  "Playwrite BE VLG",
  "Playwrite BE WAL Guides",
  "Playwrite BR Guides",
  "Playwrite BR",
  "Playwrite CA Guides",
  "Playwrite CL",
  "Playwrite CA",
  "Playwrite CO",
  "Playwrite CO Guides",
  "Playwrite CL Guides",
  "Playwrite CU",
  "Playwrite CZ",
  "Playwrite CU Guides",
  "Playwrite CZ Guides",
  "Playwrite DE Grund",
  "Playwrite DE Grund Guides",
  "Playwrite DE LA Guides",
  "Playwrite DE LA",
  "Playwrite DE VA",
  "Playwrite DE SAS Guides",
  "Playwrite DE SAS",
  "Playwrite DE VA Guides",
  "Playwrite DK Loopet",
  "Playwrite DK Loopet Guides",
  "Playwrite DK Uloopet",
  "Playwrite ES",
  "Playwrite DK Uloopet Guides",
  "Playwrite ES Deco Guides",
  "Playwrite ES Deco",
  "Playwrite ES Guides",
  "Playwrite FR Moderne",
  "Playwrite FR Moderne Guides",
  "Playwrite FR Trad Guides",
  "Playwrite FR Trad",
  "Playwrite GB J",
  "Playwrite GB J Guides",
  "Playwrite HR",
  "Playwrite GB S Guides",
  "Playwrite GB S",
  "Playwrite HR Guides",
  "Playwrite HR Lijeva",
  "Playwrite HR Lijeva Guides",
  "Playwrite HU",
  "Playwrite HU Guides",
  "Playwrite ID Guides",
  "Playwrite IE Guides",
  "Playwrite ID",
  "Playwrite IE",
  "Playwrite IS Guides",
  "Playwrite IN Guides",
  "Playwrite IS",
  "Playwrite IN",
  "Playwrite IT Moderna Guides",
  "Playwrite IT Moderna",
  "Playwrite IT Trad Guides",
  "Playwrite MX",
  "Playwrite NG Modern Guides",
  "Playwrite IT Trad",
  "Playwrite MX Guides",
  "Playwrite NG Modern",
  "Playwrite NL",
  "Playwrite NL Guides",
  "Playwrite NO",
  "Playwrite NO Guides",
  "Playwrite PE Guides",
  "Playwrite NZ",
  "Playwrite PE",
  "Playwrite NZ Guides",
  "Playwrite PL",
  "Playwrite PL Guides",
  "Playwrite PT",
  "Playwrite SK Guides",
  "Playwrite PT Guides",
  "Playwrite RO Guides",
  "Playwrite RO",
  "Playwrite SK",
  "Playwrite TZ",
  "Playwrite US Modern Guides",
  "Playwrite TZ Guides",
  "Playwrite US Modern",
  "Playwrite US Trad",
  "Playwrite VN Guides",
  "Playwrite VN",
  "Playwrite ZA",
  "Playwrite US Trad Guides",
  "Playwrite ZA Guides",
  "Wavefont"
];