export const incompatibleFonts = [
  "Chiron GoRound TC",
  "Chiron Sung HK",
  "Chiron Hei HK",
  "Linefont",
  "Material Icons",
  "Material Icons Round",
  "Material Icons Outlined",
  "Material Icons Two Tone",
  "Material Symbols Rounded",
  "Material Symbols Sharp",
  "Material Symbols Outlined",
  "Material Icons Sharp",
  "Material Symbols",
  "Playwrite AR",
  "Playwrite AR Guides",
  "Playwrite AT",
  "Playwrite AU NSW Guides",
  "Playwrite AU QLD",
  "Playwrite AT Guides",
  "Playwrite AU NSW",
  "Playwrite AU QLD Guides",
  "Playwrite AU SA Guides",
  "Playwrite AU SA",
  "Playwrite AU TAS",
  "Playwrite AU TAS Guides",
  "Playwrite AU VIC Guides",
  "Playwrite BE VLG",
  "Playwrite BE VLG Guides",
  "Playwrite AU VIC",
  "Playwrite BE WAL",
  "Playwrite BE WAL Guides",
  "Playwrite BR",
  "Playwrite BR Guides",
  "Playwrite CA",
  "Playwrite CA Guides",
  "Playwrite CU",
  "Playwrite CO Guides",
  "Playwrite CL Guides",
  "Playwrite CO",
  "Playwrite CZ Guides",
  "Playwrite DE Grund",
  "Playwrite DE Grund Guides",
  "Playwrite DE LA",
  "Playwrite DE LA Guides",
  "Playwrite CZ",
  "Playwrite CU Guides",
  "Playwrite CL",
  "Playwrite DE SAS",
  "Playwrite DE SAS Guides",
  "Playwrite DE VA Guides",
  "Playwrite DK Loopet",
  "Playwrite DK Uloopet Guides",
  "Playwrite DK Uloopet",
  "Playwrite DE VA",
  "Playwrite ES Deco",
  "Playwrite ES",
  "Playwrite ES Guides",
  "Playwrite FR Moderne Guides",
  "Playwrite ES Deco Guides",
  "Playwrite FR Trad",
  "Playwrite FR Trad Guides",
  "Playwrite GB J Guides",
  "Playwrite GB S",
  "Playwrite GB J",
  "Playwrite FR Moderne",
  "Playwrite HR",
  "Playwrite DK Loopet Guides",
  "Playwrite HR Guides",
  "Playwrite HR Lijeva",
  "Playwrite HU",
  "Playwrite HR Lijeva Guides",
  "Playwrite ID",
  "Playwrite HU Guides",
  "Playwrite IE",
  "Playwrite IN",
  "Playwrite ID Guides",
  "Playwrite IS Guides",
  "Playwrite GB S Guides",
  "Playwrite IT Moderna",
  "Playwrite IN Guides",
  "Playwrite IE Guides",
  "Playwrite IT Moderna Guides",
  "Playwrite IT Trad",
  "Playwrite IT Trad Guides",
  "Playwrite IS",
  "Playwrite MX Guides",
  "Playwrite NG Modern",
  "Playwrite NG Modern Guides",
  "Playwrite NL Guides",
  "Playwrite MX",
  "Playwrite NL",
  "Playwrite NO Guides",
  "Playwrite NZ Basic Guides",
  "Playwrite NZ",
  "Playwrite PE",
  "Playwrite NZ Guides",
  "Playwrite PL",
  "Playwrite PT Guides",
  "Playwrite NZ Basic",
  "Playwrite NO",
  "Playwrite RO",
  "Playwrite PL Guides",
  "Playwrite RO Guides",
  "Playwrite SK",
  "Playwrite SK Guides",
  "Playwrite TZ",
  "Playwrite PE Guides",
  "Playwrite TZ Guides",
  "Playwrite PT",
  "Playwrite US Modern Guides",
  "Playwrite US Modern",
  "Playwrite US Trad Guides",
  "Playwrite US Trad",
  "Playwrite VN",
  "Playwrite VN Guides",
  "Playwrite ZA",
  "Playwrite ZA Guides",
  "Wavefont"
];