// bun --env-file=.env scripts/update-font-db.ts

import {$} from 'bun';

const [staticResponse, variableResponse] = await Promise.all([
	fetch(
		`https://content-webfonts.googleapis.com/v1/webfonts?capability=WOFF2&key=${process.env.GOOGLE_FONTS_API_KEY}`,
	),
	fetch(
		`https://content-webfonts.googleapis.com/v1/webfonts?capability=VF&capability=WOFF2&key=${process.env.GOOGLE_FONTS_API_KEY}`,
	),
]);

const staticJson = await staticResponse.json();
const variableJson = await variableResponse.json();
const variableFonts = new Map<
	string,
	{
		family: string;
		axes?: {tag: string; start: number; end: number}[];
	}
>(
	variableJson.items.map(
		(font: {
			family: string;
			axes?: {tag: string; start: number; end: number}[];
		}) => [font.family, font] as const,
	),
);
const items = staticJson.items.map((font: {family: string}) => {
	const axes = variableFonts.get(font.family)?.axes;
	return axes ? {...font, axes} : font;
});

const contents = `
// Auto-generated by scripts/update-font-db.ts

export type Font = {
  family: string;
  variants: string[];
  subsets: string[];
  version: string;
  lastModified: string;
  category: string;
  axes?: {tag: string; start: number; end: number}[];
  colorCapabilities?: unknown;
  files?: unknown;
  kind?: unknown;
  menu?: unknown;
};

export const googleFonts: Font[] = ${JSON.stringify(items, null, 2)};
`.trimStart();

await Bun.write(__dirname + '/google-fonts.ts', contents);
await $`bunx prettier --write ${__dirname}/google-fonts.ts`;

const packageJson = JSON.parse(await Bun.file('package.json').text());
packageJson.typesVersions['>=1.0'] = {};
await Bun.write('package.json', JSON.stringify(packageJson, null, 2));

await $`bun scripts/generate.ts && bun scripts/generate-index.ts`;
await $`bunx prettier --write src`;
await $`bun run make`;
await $`bun ensure-generation.ts`;

export {};
