// Auto-generated by packages/studio/scripts/generate-google-font-info.ts
export const GOOGLE_FONTS_LIST = [
	{
		importName: 'ABeeZee',
		fontFamily: 'ABeeZee',
		previewUrl: 'ABeeZee',
	},
	{
		importName: 'Abel',
		fontFamily: 'Abel',
		previewUrl: 'Abel',
	},
	{
		importName: 'AbrilFatface',
		fontFamily: 'Abril Fatface',
		previewUrl: 'Abril+Fatface',
	},
	{
		importName: 'Acme',
		fontFamily: 'Acme',
		previewUrl: 'Acme',
	},
	{
		importName: 'Alata',
		fontFamily: 'Alata',
		previewUrl: 'Alata',
	},
	{
		importName: 'AlbertSans',
		fontFamily: 'Albert Sans',
		previewUrl: 'Albert+Sans',
	},
	{
		importName: 'Alegreya',
		fontFamily: 'Alegreya',
		previewUrl: 'Alegreya',
	},
	{
		importName: 'AlegreyaSans',
		fontFamily: 'Alegreya Sans',
		previewUrl: 'Alegreya+Sans',
	},
	{
		importName: 'AlegreyaSansSC',
		fontFamily: 'Alegreya Sans SC',
		previewUrl: 'Alegreya+Sans+SC',
	},
	{
		importName: 'AlfaSlabOne',
		fontFamily: 'Alfa Slab One',
		previewUrl: 'Alfa+Slab+One',
	},
	{
		importName: 'Alice',
		fontFamily: 'Alice',
		previewUrl: 'Alice',
	},
	{
		importName: 'Almarai',
		fontFamily: 'Almarai',
		previewUrl: 'Almarai',
	},
	{
		importName: 'AmaticSC',
		fontFamily: 'Amatic SC',
		previewUrl: 'Amatic+SC',
	},
	{
		importName: 'Amiri',
		fontFamily: 'Amiri',
		previewUrl: 'Amiri',
	},
	{
		importName: 'AnticSlab',
		fontFamily: 'Antic Slab',
		previewUrl: 'Antic+Slab',
	},
	{
		importName: 'Anton',
		fontFamily: 'Anton',
		previewUrl: 'Anton',
	},
	{
		importName: 'ArchitectsDaughter',
		fontFamily: 'Architects Daughter',
		previewUrl: 'Architects+Daughter',
	},
	{
		importName: 'Archivo',
		fontFamily: 'Archivo',
		previewUrl: 'Archivo',
	},
	{
		importName: 'ArchivoBlack',
		fontFamily: 'Archivo Black',
		previewUrl: 'Archivo+Black',
	},
	{
		importName: 'ArchivoNarrow',
		fontFamily: 'Archivo Narrow',
		previewUrl: 'Archivo+Narrow',
	},
	{
		importName: 'Arimo',
		fontFamily: 'Arimo',
		previewUrl: 'Arimo',
	},
	{
		importName: 'Arsenal',
		fontFamily: 'Arsenal',
		previewUrl: 'Arsenal',
	},
	{
		importName: 'Arvo',
		fontFamily: 'Arvo',
		previewUrl: 'Arvo',
	},
	{
		importName: 'Asap',
		fontFamily: 'Asap',
		previewUrl: 'Asap',
	},
	{
		importName: 'AsapCondensed',
		fontFamily: 'Asap Condensed',
		previewUrl: 'Asap+Condensed',
	},
	{
		importName: 'Assistant',
		fontFamily: 'Assistant',
		previewUrl: 'Assistant',
	},
	{
		importName: 'Barlow',
		fontFamily: 'Barlow',
		previewUrl: 'Barlow',
	},
	{
		importName: 'BarlowCondensed',
		fontFamily: 'Barlow Condensed',
		previewUrl: 'Barlow+Condensed',
	},
	{
		importName: 'BarlowSemiCondensed',
		fontFamily: 'Barlow Semi Condensed',
		previewUrl: 'Barlow+Semi+Condensed',
	},
	{
		importName: 'BeVietnamPro',
		fontFamily: 'Be Vietnam Pro',
		previewUrl: 'Be+Vietnam+Pro',
	},
	{
		importName: 'BebasNeue',
		fontFamily: 'Bebas Neue',
		previewUrl: 'Bebas+Neue',
	},
	{
		importName: 'Bitter',
		fontFamily: 'Bitter',
		previewUrl: 'Bitter',
	},
	{
		importName: 'BlackOpsOne',
		fontFamily: 'Black Ops One',
		previewUrl: 'Black+Ops+One',
	},
	{
		importName: 'BodoniModa',
		fontFamily: 'Bodoni Moda',
		previewUrl: 'Bodoni+Moda',
	},
	{
		importName: 'BreeSerif',
		fontFamily: 'Bree Serif',
		previewUrl: 'Bree+Serif',
	},
	{
		importName: 'Bungee',
		fontFamily: 'Bungee',
		previewUrl: 'Bungee',
	},
	{
		importName: 'Cabin',
		fontFamily: 'Cabin',
		previewUrl: 'Cabin',
	},
	{
		importName: 'Cairo',
		fontFamily: 'Cairo',
		previewUrl: 'Cairo',
	},
	{
		importName: 'Cantarell',
		fontFamily: 'Cantarell',
		previewUrl: 'Cantarell',
	},
	{
		importName: 'Cardo',
		fontFamily: 'Cardo',
		previewUrl: 'Cardo',
	},
	{
		importName: 'Catamaran',
		fontFamily: 'Catamaran',
		previewUrl: 'Catamaran',
	},
	{
		importName: 'Caveat',
		fontFamily: 'Caveat',
		previewUrl: 'Caveat',
	},
	{
		importName: 'ChakraPetch',
		fontFamily: 'Chakra Petch',
		previewUrl: 'Chakra+Petch',
	},
	{
		importName: 'Changa',
		fontFamily: 'Changa',
		previewUrl: 'Changa',
	},
	{
		importName: 'Chivo',
		fontFamily: 'Chivo',
		previewUrl: 'Chivo',
	},
	{
		importName: 'Cinzel',
		fontFamily: 'Cinzel',
		previewUrl: 'Cinzel',
	},
	{
		importName: 'Comfortaa',
		fontFamily: 'Comfortaa',
		previewUrl: 'Comfortaa',
	},
	{
		importName: 'Commissioner',
		fontFamily: 'Commissioner',
		previewUrl: 'Commissioner',
	},
	{
		importName: 'ConcertOne',
		fontFamily: 'Concert One',
		previewUrl: 'Concert+One',
	},
	{
		importName: 'Cookie',
		fontFamily: 'Cookie',
		previewUrl: 'Cookie',
	},
	{
		importName: 'Cormorant',
		fontFamily: 'Cormorant',
		previewUrl: 'Cormorant',
	},
	{
		importName: 'CormorantGaramond',
		fontFamily: 'Cormorant Garamond',
		previewUrl: 'Cormorant+Garamond',
	},
	{
		importName: 'Courgette',
		fontFamily: 'Courgette',
		previewUrl: 'Courgette',
	},
	{
		importName: 'CreteRound',
		fontFamily: 'Crete Round',
		previewUrl: 'Crete+Round',
	},
	{
		importName: 'CrimsonPro',
		fontFamily: 'Crimson Pro',
		previewUrl: 'Crimson+Pro',
	},
	{
		importName: 'CrimsonText',
		fontFamily: 'Crimson Text',
		previewUrl: 'Crimson+Text',
	},
	{
		importName: 'Cuprum',
		fontFamily: 'Cuprum',
		previewUrl: 'Cuprum',
	},
	{
		importName: 'DMSans',
		fontFamily: 'DM Sans',
		previewUrl: 'DM+Sans',
	},
	{
		importName: 'DMSerifDisplay',
		fontFamily: 'DM Serif Display',
		previewUrl: 'DM+Serif+Display',
	},
	{
		importName: 'DMSerifText',
		fontFamily: 'DM Serif Text',
		previewUrl: 'DM+Serif+Text',
	},
	{
		importName: 'DancingScript',
		fontFamily: 'Dancing Script',
		previewUrl: 'Dancing+Script',
	},
	{
		importName: 'DidactGothic',
		fontFamily: 'Didact Gothic',
		previewUrl: 'Didact+Gothic',
	},
	{
		importName: 'Domine',
		fontFamily: 'Domine',
		previewUrl: 'Domine',
	},
	{
		importName: 'Dosis',
		fontFamily: 'Dosis',
		previewUrl: 'Dosis',
	},
	{
		importName: 'EBGaramond',
		fontFamily: 'EB Garamond',
		previewUrl: 'EB+Garamond',
	},
	{
		importName: 'Eczar',
		fontFamily: 'Eczar',
		previewUrl: 'Eczar',
	},
	{
		importName: 'ElMessiri',
		fontFamily: 'El Messiri',
		previewUrl: 'El+Messiri',
	},
	{
		importName: 'Electrolize',
		fontFamily: 'Electrolize',
		previewUrl: 'Electrolize',
	},
	{
		importName: 'EncodeSans',
		fontFamily: 'Encode Sans',
		previewUrl: 'Encode+Sans',
	},
	{
		importName: 'EncodeSansCondensed',
		fontFamily: 'Encode Sans Condensed',
		previewUrl: 'Encode+Sans+Condensed',
	},
	{
		importName: 'Exo',
		fontFamily: 'Exo',
		previewUrl: 'Exo',
	},
	{
		importName: 'Exo2',
		fontFamily: 'Exo Two',
		previewUrl: 'Exo+2',
	},
	{
		importName: 'Figtree',
		fontFamily: 'Figtree',
		previewUrl: 'Figtree',
	},
	{
		importName: 'FiraSans',
		fontFamily: 'Fira Sans',
		previewUrl: 'Fira+Sans',
	},
	{
		importName: 'FiraSansCondensed',
		fontFamily: 'Fira Sans Condensed',
		previewUrl: 'Fira+Sans+Condensed',
	},
	{
		importName: 'FjallaOne',
		fontFamily: 'Fjalla One',
		previewUrl: 'Fjalla+One',
	},
	{
		importName: 'FrancoisOne',
		fontFamily: 'Francois One',
		previewUrl: 'Francois+One',
	},
	{
		importName: 'FrankRuhlLibre',
		fontFamily: 'Frank Ruhl Libre',
		previewUrl: 'Frank+Ruhl+Libre',
	},
	{
		importName: 'Fraunces',
		fontFamily: 'Fraunces',
		previewUrl: 'Fraunces',
	},
	{
		importName: 'Gelasio',
		fontFamily: 'Gelasio',
		previewUrl: 'Gelasio',
	},
	{
		importName: 'GloriaHallelujah',
		fontFamily: 'Gloria Hallelujah',
		previewUrl: 'Gloria+Hallelujah',
	},
	{
		importName: 'GothicA1',
		fontFamily: 'Gothic AOne',
		previewUrl: 'Gothic+A1',
	},
	{
		importName: 'GreatVibes',
		fontFamily: 'Great Vibes',
		previewUrl: 'Great+Vibes',
	},
	{
		importName: 'Gruppo',
		fontFamily: 'Gruppo',
		previewUrl: 'Gruppo',
	},
	{
		importName: 'Heebo',
		fontFamily: 'Heebo',
		previewUrl: 'Heebo',
	},
	{
		importName: 'Hind',
		fontFamily: 'Hind',
		previewUrl: 'Hind',
	},
	{
		importName: 'HindMadurai',
		fontFamily: 'Hind Madurai',
		previewUrl: 'Hind+Madurai',
	},
	{
		importName: 'HindSiliguri',
		fontFamily: 'Hind Siliguri',
		previewUrl: 'Hind+Siliguri',
	},
	{
		importName: 'IBMPlexMono',
		fontFamily: 'IBM Plex Mono',
		previewUrl: 'IBM+Plex+Mono',
	},
	{
		importName: 'IBMPlexSans',
		fontFamily: 'IBM Plex Sans',
		previewUrl: 'IBM+Plex+Sans',
	},
	{
		importName: 'IBMPlexSansArabic',
		fontFamily: 'IBM Plex Sans Arabic',
		previewUrl: 'IBM+Plex+Sans+Arabic',
	},
	{
		importName: 'IBMPlexSansCondensed',
		fontFamily: 'IBM Plex Sans Condensed',
		previewUrl: 'IBM+Plex+Sans+Condensed',
	},
	{
		importName: 'IBMPlexSerif',
		fontFamily: 'IBM Plex Serif',
		previewUrl: 'IBM+Plex+Serif',
	},
	{
		importName: 'Inconsolata',
		fontFamily: 'Inconsolata',
		previewUrl: 'Inconsolata',
	},
	{
		importName: 'IndieFlower',
		fontFamily: 'Indie Flower',
		previewUrl: 'Indie+Flower',
	},
	{
		importName: 'Inter',
		fontFamily: 'Inter',
		previewUrl: 'Inter',
	},
	{
		importName: 'InterTight',
		fontFamily: 'Inter Tight',
		previewUrl: 'Inter+Tight',
	},
	{
		importName: 'JosefinSans',
		fontFamily: 'Josefin Sans',
		previewUrl: 'Josefin+Sans',
	},
	{
		importName: 'JosefinSlab',
		fontFamily: 'Josefin Slab',
		previewUrl: 'Josefin+Slab',
	},
	{
		importName: 'Jost',
		fontFamily: 'Jost',
		previewUrl: 'Jost',
	},
	{
		importName: 'Kalam',
		fontFamily: 'Kalam',
		previewUrl: 'Kalam',
	},
	{
		importName: 'Kanit',
		fontFamily: 'Kanit',
		previewUrl: 'Kanit',
	},
	{
		importName: 'Karla',
		fontFamily: 'Karla',
		previewUrl: 'Karla',
	},
	{
		importName: 'KaushanScript',
		fontFamily: 'Kaushan Script',
		previewUrl: 'Kaushan+Script',
	},
	{
		importName: 'Khand',
		fontFamily: 'Khand',
		previewUrl: 'Khand',
	},
	{
		importName: 'Lato',
		fontFamily: 'Lato',
		previewUrl: 'Lato',
	},
	{
		importName: 'LeagueSpartan',
		fontFamily: 'League Spartan',
		previewUrl: 'League+Spartan',
	},
	{
		importName: 'Lexend',
		fontFamily: 'Lexend',
		previewUrl: 'Lexend',
	},
	{
		importName: 'LexendDeca',
		fontFamily: 'Lexend Deca',
		previewUrl: 'Lexend+Deca',
	},
	{
		importName: 'LibreBarcode39',
		fontFamily: 'Libre Barcode ThreeNine',
		previewUrl: 'Libre+Barcode+39',
	},
	{
		importName: 'LibreBaskerville',
		fontFamily: 'Libre Baskerville',
		previewUrl: 'Libre+Baskerville',
	},
	{
		importName: 'LibreCaslonText',
		fontFamily: 'Libre Caslon Text',
		previewUrl: 'Libre+Caslon+Text',
	},
	{
		importName: 'LibreFranklin',
		fontFamily: 'Libre Franklin',
		previewUrl: 'Libre+Franklin',
	},
	{
		importName: 'LilitaOne',
		fontFamily: 'Lilita One',
		previewUrl: 'Lilita+One',
	},
	{
		importName: 'Lobster',
		fontFamily: 'Lobster',
		previewUrl: 'Lobster',
	},
	{
		importName: 'LobsterTwo',
		fontFamily: 'Lobster Two',
		previewUrl: 'Lobster+Two',
	},
	{
		importName: 'Lora',
		fontFamily: 'Lora',
		previewUrl: 'Lora',
	},
	{
		importName: 'LuckiestGuy',
		fontFamily: 'Luckiest Guy',
		previewUrl: 'Luckiest+Guy',
	},
	{
		importName: 'MPLUS1p',
		fontFamily: 'M PLUS Onep',
		previewUrl: 'M+PLUS+1p',
	},
	{
		importName: 'MPLUSRounded1c',
		fontFamily: 'M PLUS Rounded Onec',
		previewUrl: 'M+PLUS+Rounded+1c',
	},
	{
		importName: 'Macondo',
		fontFamily: 'Macondo',
		previewUrl: 'Macondo',
	},
	{
		importName: 'Manrope',
		fontFamily: 'Manrope',
		previewUrl: 'Manrope',
	},
	{
		importName: 'Marcellus',
		fontFamily: 'Marcellus',
		previewUrl: 'Marcellus',
	},
	{
		importName: 'Martel',
		fontFamily: 'Martel',
		previewUrl: 'Martel',
	},
	{
		importName: 'Mate',
		fontFamily: 'Mate',
		previewUrl: 'Mate',
	},
	{
		importName: 'MateSC',
		fontFamily: 'Mate SC',
		previewUrl: 'Mate+SC',
	},
	{
		importName: 'MavenPro',
		fontFamily: 'Maven Pro',
		previewUrl: 'Maven+Pro',
	},
	{
		importName: 'Merienda',
		fontFamily: 'Merienda',
		previewUrl: 'Merienda',
	},
	{
		importName: 'Merriweather',
		fontFamily: 'Merriweather',
		previewUrl: 'Merriweather',
	},
	{
		importName: 'MerriweatherSans',
		fontFamily: 'Merriweather Sans',
		previewUrl: 'Merriweather+Sans',
	},
	{
		importName: 'Montserrat',
		fontFamily: 'Montserrat',
		previewUrl: 'Montserrat',
	},
	{
		importName: 'MontserratAlternates',
		fontFamily: 'Montserrat Alternates',
		previewUrl: 'Montserrat+Alternates',
	},
	{
		importName: 'Mukta',
		fontFamily: 'Mukta',
		previewUrl: 'Mukta',
	},
	{
		importName: 'Mulish',
		fontFamily: 'Mulish',
		previewUrl: 'Mulish',
	},
	{
		importName: 'NanumGothic',
		fontFamily: 'Nanum Gothic',
		previewUrl: 'Nanum+Gothic',
	},
	{
		importName: 'NanumGothicCoding',
		fontFamily: 'Nanum Gothic Coding',
		previewUrl: 'Nanum+Gothic+Coding',
	},
	{
		importName: 'NanumMyeongjo',
		fontFamily: 'Nanum Myeongjo',
		previewUrl: 'Nanum+Myeongjo',
	},
	{
		importName: 'Neuton',
		fontFamily: 'Neuton',
		previewUrl: 'Neuton',
	},
	{
		importName: 'NoticiaText',
		fontFamily: 'Noticia Text',
		previewUrl: 'Noticia+Text',
	},
	{
		importName: 'NotoColorEmoji',
		fontFamily: 'Noto Color Emoji',
		previewUrl: 'Noto+Color+Emoji',
	},
	{
		importName: 'NotoKufiArabic',
		fontFamily: 'Noto Kufi Arabic',
		previewUrl: 'Noto+Kufi+Arabic',
	},
	{
		importName: 'NotoNaskhArabic',
		fontFamily: 'Noto Naskh Arabic',
		previewUrl: 'Noto+Naskh+Arabic',
	},
	{
		importName: 'NotoSans',
		fontFamily: 'Noto Sans',
		previewUrl: 'Noto+Sans',
	},
	{
		importName: 'NotoSansArabic',
		fontFamily: 'Noto Sans Arabic',
		previewUrl: 'Noto+Sans+Arabic',
	},
	{
		importName: 'NotoSansBengali',
		fontFamily: 'Noto Sans Bengali',
		previewUrl: 'Noto+Sans+Bengali',
	},
	{
		importName: 'NotoSansDisplay',
		fontFamily: 'Noto Sans Display',
		previewUrl: 'Noto+Sans+Display',
	},
	{
		importName: 'NotoSansHK',
		fontFamily: 'Noto Sans HK',
		previewUrl: 'Noto+Sans+HK',
	},
	{
		importName: 'NotoSansJP',
		fontFamily: 'Noto Sans JP',
		previewUrl: 'Noto+Sans+JP',
	},
	{
		importName: 'NotoSansKR',
		fontFamily: 'Noto Sans KR',
		previewUrl: 'Noto+Sans+KR',
	},
	{
		importName: 'NotoSansMono',
		fontFamily: 'Noto Sans Mono',
		previewUrl: 'Noto+Sans+Mono',
	},
	{
		importName: 'NotoSansSC',
		fontFamily: 'Noto Sans SC',
		previewUrl: 'Noto+Sans+SC',
	},
	{
		importName: 'NotoSansTC',
		fontFamily: 'Noto Sans TC',
		previewUrl: 'Noto+Sans+TC',
	},
	{
		importName: 'NotoSansThai',
		fontFamily: 'Noto Sans Thai',
		previewUrl: 'Noto+Sans+Thai',
	},
	{
		importName: 'NotoSerif',
		fontFamily: 'Noto Serif',
		previewUrl: 'Noto+Serif',
	},
	{
		importName: 'NotoSerifJP',
		fontFamily: 'Noto Serif JP',
		previewUrl: 'Noto+Serif+JP',
	},
	{
		importName: 'NotoSerifKR',
		fontFamily: 'Noto Serif KR',
		previewUrl: 'Noto+Serif+KR',
	},
	{
		importName: 'NotoSerifTC',
		fontFamily: 'Noto Serif TC',
		previewUrl: 'Noto+Serif+TC',
	},
	{
		importName: 'Nunito',
		fontFamily: 'Nunito',
		previewUrl: 'Nunito',
	},
	{
		importName: 'NunitoSans',
		fontFamily: 'Nunito Sans',
		previewUrl: 'Nunito+Sans',
	},
	{
		importName: 'OldStandardTT',
		fontFamily: 'Old Standard TT',
		previewUrl: 'Old+Standard+TT',
	},
	{
		importName: 'OleoScript',
		fontFamily: 'Oleo Script',
		previewUrl: 'Oleo+Script',
	},
	{
		importName: 'OpenSans',
		fontFamily: 'Open Sans',
		previewUrl: 'Open+Sans',
	},
	{
		importName: 'Orbitron',
		fontFamily: 'Orbitron',
		previewUrl: 'Orbitron',
	},
	{
		importName: 'Oswald',
		fontFamily: 'Oswald',
		previewUrl: 'Oswald',
	},
	{
		importName: 'Outfit',
		fontFamily: 'Outfit',
		previewUrl: 'Outfit',
	},
	{
		importName: 'Overpass',
		fontFamily: 'Overpass',
		previewUrl: 'Overpass',
	},
	{
		importName: 'Oxygen',
		fontFamily: 'Oxygen',
		previewUrl: 'Oxygen',
	},
	{
		importName: 'PTSans',
		fontFamily: 'PT Sans',
		previewUrl: 'PT+Sans',
	},
	{
		importName: 'PTSansCaption',
		fontFamily: 'PT Sans Caption',
		previewUrl: 'PT+Sans+Caption',
	},
	{
		importName: 'PTSansNarrow',
		fontFamily: 'PT Sans Narrow',
		previewUrl: 'PT+Sans+Narrow',
	},
	{
		importName: 'PTSerif',
		fontFamily: 'PT Serif',
		previewUrl: 'PT+Serif',
	},
	{
		importName: 'Pacifico',
		fontFamily: 'Pacifico',
		previewUrl: 'Pacifico',
	},
	{
		importName: 'PassionOne',
		fontFamily: 'Passion One',
		previewUrl: 'Passion+One',
	},
	{
		importName: 'PathwayGothicOne',
		fontFamily: 'Pathway Gothic One',
		previewUrl: 'Pathway+Gothic+One',
	},
	{
		importName: 'PatuaOne',
		fontFamily: 'Patua One',
		previewUrl: 'Patua+One',
	},
	{
		importName: 'PaytoneOne',
		fontFamily: 'Paytone One',
		previewUrl: 'Paytone+One',
	},
	{
		importName: 'PermanentMarker',
		fontFamily: 'Permanent Marker',
		previewUrl: 'Permanent+Marker',
	},
	{
		importName: 'Philosopher',
		fontFamily: 'Philosopher',
		previewUrl: 'Philosopher',
	},
	{
		importName: 'Play',
		fontFamily: 'Play',
		previewUrl: 'Play',
	},
	{
		importName: 'PlayfairDisplay',
		fontFamily: 'Playfair Display',
		previewUrl: 'Playfair+Display',
	},
	{
		importName: 'PlusJakartaSans',
		fontFamily: 'Plus Jakarta Sans',
		previewUrl: 'Plus+Jakarta+Sans',
	},
	{
		importName: 'Poppins',
		fontFamily: 'Poppins',
		previewUrl: 'Poppins',
	},
	{
		importName: 'Prata',
		fontFamily: 'Prata',
		previewUrl: 'Prata',
	},
	{
		importName: 'Prompt',
		fontFamily: 'Prompt',
		previewUrl: 'Prompt',
	},
	{
		importName: 'PublicSans',
		fontFamily: 'Public Sans',
		previewUrl: 'Public+Sans',
	},
	{
		importName: 'Quattrocento',
		fontFamily: 'Quattrocento',
		previewUrl: 'Quattrocento',
	},
	{
		importName: 'QuattrocentoSans',
		fontFamily: 'Quattrocento Sans',
		previewUrl: 'Quattrocento+Sans',
	},
	{
		importName: 'Questrial',
		fontFamily: 'Questrial',
		previewUrl: 'Questrial',
	},
	{
		importName: 'Quicksand',
		fontFamily: 'Quicksand',
		previewUrl: 'Quicksand',
	},
	{
		importName: 'Rajdhani',
		fontFamily: 'Rajdhani',
		previewUrl: 'Rajdhani',
	},
	{
		importName: 'Raleway',
		fontFamily: 'Raleway',
		previewUrl: 'Raleway',
	},
	{
		importName: 'ReadexPro',
		fontFamily: 'Readex Pro',
		previewUrl: 'Readex+Pro',
	},
	{
		importName: 'RedHatDisplay',
		fontFamily: 'Red Hat Display',
		previewUrl: 'Red+Hat+Display',
	},
	{
		importName: 'Righteous',
		fontFamily: 'Righteous',
		previewUrl: 'Righteous',
	},
	{
		importName: 'Roboto',
		fontFamily: 'Roboto',
		previewUrl: 'Roboto',
	},
	{
		importName: 'RobotoCondensed',
		fontFamily: 'Roboto Condensed',
		previewUrl: 'Roboto+Condensed',
	},
	{
		importName: 'RobotoFlex',
		fontFamily: 'Roboto Flex',
		previewUrl: 'Roboto+Flex',
	},
	{
		importName: 'RobotoMono',
		fontFamily: 'Roboto Mono',
		previewUrl: 'Roboto+Mono',
	},
	{
		importName: 'RobotoSerif',
		fontFamily: 'Roboto Serif',
		previewUrl: 'Roboto+Serif',
	},
	{
		importName: 'RobotoSlab',
		fontFamily: 'Roboto Slab',
		previewUrl: 'Roboto+Slab',
	},
	{
		importName: 'Rokkitt',
		fontFamily: 'Rokkitt',
		previewUrl: 'Rokkitt',
	},
	{
		importName: 'Rowdies',
		fontFamily: 'Rowdies',
		previewUrl: 'Rowdies',
	},
	{
		importName: 'Rubik',
		fontFamily: 'Rubik',
		previewUrl: 'Rubik',
	},
	{
		importName: 'RubikBubbles',
		fontFamily: 'Rubik Bubbles',
		previewUrl: 'Rubik+Bubbles',
	},
	{
		importName: 'RubikMonoOne',
		fontFamily: 'Rubik Mono One',
		previewUrl: 'Rubik+Mono+One',
	},
	{
		importName: 'RussoOne',
		fontFamily: 'Russo One',
		previewUrl: 'Russo+One',
	},
	{
		importName: 'Sacramento',
		fontFamily: 'Sacramento',
		previewUrl: 'Sacramento',
	},
	{
		importName: 'Saira',
		fontFamily: 'Saira',
		previewUrl: 'Saira',
	},
	{
		importName: 'SairaCondensed',
		fontFamily: 'Saira Condensed',
		previewUrl: 'Saira+Condensed',
	},
	{
		importName: 'Sarabun',
		fontFamily: 'Sarabun',
		previewUrl: 'Sarabun',
	},
	{
		importName: 'Satisfy',
		fontFamily: 'Satisfy',
		previewUrl: 'Satisfy',
	},
	{
		importName: 'SawarabiGothic',
		fontFamily: 'Sawarabi Gothic',
		previewUrl: 'Sawarabi+Gothic',
	},
	{
		importName: 'SawarabiMincho',
		fontFamily: 'Sawarabi Mincho',
		previewUrl: 'Sawarabi+Mincho',
	},
	{
		importName: 'Sen',
		fontFamily: 'Sen',
		previewUrl: 'Sen',
	},
	{
		importName: 'ShadowsIntoLight',
		fontFamily: 'Shadows Into Light',
		previewUrl: 'Shadows+Into+Light',
	},
	{
		importName: 'Signika',
		fontFamily: 'Signika',
		previewUrl: 'Signika',
	},
	{
		importName: 'SignikaNegative',
		fontFamily: 'Signika Negative',
		previewUrl: 'Signika+Negative',
	},
	{
		importName: 'Silkscreen',
		fontFamily: 'Silkscreen',
		previewUrl: 'Silkscreen',
	},
	{
		importName: 'SixCaps',
		fontFamily: 'Six Caps',
		previewUrl: 'Six+Caps',
	},
	{
		importName: 'Slabo27px',
		fontFamily: 'Slabo TwoSevenpx',
		previewUrl: 'Slabo+27px',
	},
	{
		importName: 'Sora',
		fontFamily: 'Sora',
		previewUrl: 'Sora',
	},
	{
		importName: 'SourceCodePro',
		fontFamily: 'Source Code Pro',
		previewUrl: 'Source+Code+Pro',
	},
	{
		importName: 'SourceSans3',
		fontFamily: 'Source Sans Three',
		previewUrl: 'Source+Sans+3',
	},
	{
		importName: 'SourceSerif4',
		fontFamily: 'Source Serif Four',
		previewUrl: 'Source+Serif+4',
	},
	{
		importName: 'SpaceGrotesk',
		fontFamily: 'Space Grotesk',
		previewUrl: 'Space+Grotesk',
	},
	{
		importName: 'SpaceMono',
		fontFamily: 'Space Mono',
		previewUrl: 'Space+Mono',
	},
	{
		importName: 'SpecialElite',
		fontFamily: 'Special Elite',
		previewUrl: 'Special+Elite',
	},
	{
		importName: 'Spectral',
		fontFamily: 'Spectral',
		previewUrl: 'Spectral',
	},
	{
		importName: 'Tajawal',
		fontFamily: 'Tajawal',
		previewUrl: 'Tajawal',
	},
	{
		importName: 'Tangerine',
		fontFamily: 'Tangerine',
		previewUrl: 'Tangerine',
	},
	{
		importName: 'Teko',
		fontFamily: 'Teko',
		previewUrl: 'Teko',
	},
	{
		importName: 'Tinos',
		fontFamily: 'Tinos',
		previewUrl: 'Tinos',
	},
	{
		importName: 'TitanOne',
		fontFamily: 'Titan One',
		previewUrl: 'Titan+One',
	},
	{
		importName: 'TitilliumWeb',
		fontFamily: 'Titillium Web',
		previewUrl: 'Titillium+Web',
	},
	{
		importName: 'Ubuntu',
		fontFamily: 'Ubuntu',
		previewUrl: 'Ubuntu',
	},
	{
		importName: 'UbuntuCondensed',
		fontFamily: 'Ubuntu Condensed',
		previewUrl: 'Ubuntu+Condensed',
	},
	{
		importName: 'UbuntuMono',
		fontFamily: 'Ubuntu Mono',
		previewUrl: 'Ubuntu+Mono',
	},
	{
		importName: 'Unbounded',
		fontFamily: 'Unbounded',
		previewUrl: 'Unbounded',
	},
	{
		importName: 'Unna',
		fontFamily: 'Unna',
		previewUrl: 'Unna',
	},
	{
		importName: 'Urbanist',
		fontFamily: 'Urbanist',
		previewUrl: 'Urbanist',
	},
	{
		importName: 'VarelaRound',
		fontFamily: 'Varela Round',
		previewUrl: 'Varela+Round',
	},
	{
		importName: 'Vollkorn',
		fontFamily: 'Vollkorn',
		previewUrl: 'Vollkorn',
	},
	{
		importName: 'WorkSans',
		fontFamily: 'Work Sans',
		previewUrl: 'Work+Sans',
	},
	{
		importName: 'YanoneKaffeesatz',
		fontFamily: 'Yanone Kaffeesatz',
		previewUrl: 'Yanone+Kaffeesatz',
	},
	{
		importName: 'Yantramanav',
		fontFamily: 'Yantramanav',
		previewUrl: 'Yantramanav',
	},
	{
		importName: 'Yellowtail',
		fontFamily: 'Yellowtail',
		previewUrl: 'Yellowtail',
	},
	{
		importName: 'YesevaOne',
		fontFamily: 'Yeseva One',
		previewUrl: 'Yeseva+One',
	},
	{
		importName: 'ZenKakuGothicNew',
		fontFamily: 'Zen Kaku Gothic New',
		previewUrl: 'Zen+Kaku+Gothic+New',
	},
	{
		importName: 'Zeyada',
		fontFamily: 'Zeyada',
		previewUrl: 'Zeyada',
	},
	{
		importName: 'ZillaSlab',
		fontFamily: 'Zilla Slab',
		previewUrl: 'Zilla+Slab',
	},
	{
		importName: 'TikTokSans',
		fontFamily: 'TikTok Sans',
		previewUrl: 'TikTok+Sans',
	},
];
