import type {ApiRoutes} from '@remotion/studio-shared';

// Source mutations share one command stream with undo/redo. Reads and long-running
// asset processing must remain independent of this queue.
export const sourceMutationEndpoints: ReadonlySet<keyof ApiRoutes> = new Set([
	'/api/add-composition',
	'/api/add-effect',
	'/api/add-effect-keyframe',
	'/api/add-folder',
	'/api/add-keyframes',
	'/api/add-sequence-keyframe',
	'/api/apply-visual-control-change',
	'/api/batch-update-keyframe-settings',
	'/api/delete-composition',
	'/api/delete-effect',
	'/api/delete-keyframes',
	'/api/delete-nodes',
	'/api/duplicate-composition',
	'/api/duplicate-effect',
	'/api/duplicate-nodes',
	'/api/insert-composition-element',
	'/api/insert-element',
	'/api/insert-basic-captions',
	'/api/replace-video-source',
	'/api/invalidate-bundle',
	'/api/move-composition',
	'/api/move-folder',
	'/api/move-keyframes',
	'/api/paste-effects',
	'/api/precompose-jsx-nodes',
	'/api/prepare-element-install',
	'/api/redo',
	'/api/rename-composition',
	'/api/rename-folder',
	'/api/reorder-effect',
	'/api/reorder-sequence',
	'/api/save-effect-props',
	'/api/save-multiple-effect-props',
	'/api/save-sequence-props',
	'/api/split-sequences',
	'/api/split-video-from-audio',
	'/api/undo',
	'/api/unwrap-folder',
	'/api/update-composition-metadata',
	'/api/update-default-props',
	'/api/update-effect-keyframe-settings',
	'/api/update-sequence-keyframe-settings',
	'/api/wrap-node',
]);
