import fs from 'node:fs';
import esbuild from 'esbuild';

// Bundles the AudioWorklet pitch-shifter processor (with the core WSOLA
// implementation inlined) into a string that is loaded via a Blob URL at
// runtime. Mirrors packages/gif/build.mjs.
const tmp = 'bundled-pitch-worklet.js';

esbuild.buildSync({
	entryPoints: ['src/audio/pitch-worklet/processor.ts'],
	platform: 'browser',
	bundle: true,
	outfile: tmp,
	minify: true,
	target: 'es2020',
	format: 'iife',
});

const content = fs.readFileSync(tmp, 'utf8');

fs.writeFileSync(
	'src/audio/pitch-worklet/source.ts',
	`
// Auto-generated by build.mjs
export const src =
// eslint-disable-next-line no-template-curly-in-string
  ${JSON.stringify(content)};
`.trim() + '\n',
);

fs.unlinkSync(tmp);
