import type {IsoBaseMediaBox} from '../containers/iso-base-media/base-media-box';

export const moofBoxes: IsoBaseMediaBox[] = [
	{
		type: 'regular-box',
		boxType: 'moof',
		boxSize: 772,
		children: [
			{
				type: 'regular-box',
				boxType: 'mfhd',
				boxSize: 16,
				children: [],
				offset: 1280,
			},
			{
				type: 'regular-box',
				boxType: 'traf',
				boxSize: 328,
				children: [
					{
						type: 'tfhd-box',
						version: 0,
						trackId: 1,
						baseDataOffset: 1272,
						baseSampleDescriptionIndex: 0,
						defaultSampleDuration: 512,
						defaultSampleSize: 7297,
						defaultSampleFlags: 16842752,
					},
					{type: 'tfdt-box', version: 1, baseMediaDecodeTime: 0, offset: 1340},
					{
						type: 'trun-box',
						version: 0,
						sampleCount: 30,
						dataOffset: 780,
						firstSampleFlags: 33554432,
						samples: [
							{
								sampleDuration: null,
								sampleSize: 7297,
								sampleFlags: null,
								sampleCompositionTimeOffset: 1024,
							},
							{
								sampleDuration: null,
								sampleSize: 33,
								sampleFlags: null,
								sampleCompositionTimeOffset: 2560,
							},
							{
								sampleDuration: null,
								sampleSize: 13,
								sampleFlags: null,
								sampleCompositionTimeOffset: 1024,
							},
							{
								sampleDuration: null,
								sampleSize: 13,
								sampleFlags: null,
								sampleCompositionTimeOffset: 0,
							},
							{
								sampleDuration: null,
								sampleSize: 17,
								sampleFlags: null,
								sampleCompositionTimeOffset: 512,
							},
							{
								sampleDuration: null,
								sampleSize: 1934,
								sampleFlags: null,
								sampleCompositionTimeOffset: 2560,
							},
							{
								sampleDuration: null,
								sampleSize: 68,
								sampleFlags: null,
								sampleCompositionTimeOffset: 1024,
							},
							{
								sampleDuration: null,
								sampleSize: 57,
								sampleFlags: null,
								sampleCompositionTimeOffset: 0,
							},
							{
								sampleDuration: null,
								sampleSize: 23,
								sampleFlags: null,
								sampleCompositionTimeOffset: 512,
							},
							{
								sampleDuration: null,
								sampleSize: 310,
								sampleFlags: null,
								sampleCompositionTimeOffset: 2560,
							},
							{
								sampleDuration: null,
								sampleSize: 31,
								sampleFlags: null,
								sampleCompositionTimeOffset: 1024,
							},
							{
								sampleDuration: null,
								sampleSize: 23,
								sampleFlags: null,
								sampleCompositionTimeOffset: 0,
							},
							{
								sampleDuration: null,
								sampleSize: 23,
								sampleFlags: null,
								sampleCompositionTimeOffset: 512,
							},
							{
								sampleDuration: null,
								sampleSize: 57,
								sampleFlags: null,
								sampleCompositionTimeOffset: 2560,
							},
							{
								sampleDuration: null,
								sampleSize: 19,
								sampleFlags: null,
								sampleCompositionTimeOffset: 1024,
							},
							{
								sampleDuration: null,
								sampleSize: 13,
								sampleFlags: null,
								sampleCompositionTimeOffset: 0,
							},
							{
								sampleDuration: null,
								sampleSize: 17,
								sampleFlags: null,
								sampleCompositionTimeOffset: 512,
							},
							{
								sampleDuration: null,
								sampleSize: 14,
								sampleFlags: null,
								sampleCompositionTimeOffset: 2560,
							},
							{
								sampleDuration: null,
								sampleSize: 19,
								sampleFlags: null,
								sampleCompositionTimeOffset: 1024,
							},
							{
								sampleDuration: null,
								sampleSize: 17,
								sampleFlags: null,
								sampleCompositionTimeOffset: 0,
							},
							{
								sampleDuration: null,
								sampleSize: 17,
								sampleFlags: null,
								sampleCompositionTimeOffset: 512,
							},
							{
								sampleDuration: null,
								sampleSize: 14,
								sampleFlags: null,
								sampleCompositionTimeOffset: 2560,
							},
							{
								sampleDuration: null,
								sampleSize: 19,
								sampleFlags: null,
								sampleCompositionTimeOffset: 1024,
							},
							{
								sampleDuration: null,
								sampleSize: 17,
								sampleFlags: null,
								sampleCompositionTimeOffset: 0,
							},
							{
								sampleDuration: null,
								sampleSize: 17,
								sampleFlags: null,
								sampleCompositionTimeOffset: 512,
							},
							{
								sampleDuration: null,
								sampleSize: 14,
								sampleFlags: null,
								sampleCompositionTimeOffset: 2560,
							},
							{
								sampleDuration: null,
								sampleSize: 19,
								sampleFlags: null,
								sampleCompositionTimeOffset: 1024,
							},
							{
								sampleDuration: null,
								sampleSize: 17,
								sampleFlags: null,
								sampleCompositionTimeOffset: 0,
							},
							{
								sampleDuration: null,
								sampleSize: 17,
								sampleFlags: null,
								sampleCompositionTimeOffset: 512,
							},
							{
								sampleDuration: null,
								sampleSize: 14,
								sampleFlags: null,
								sampleCompositionTimeOffset: 1024,
							},
						],
					},
				],
				offset: 1296,
			},
			{
				type: 'regular-box',
				boxType: 'traf',
				boxSize: 420,
				children: [
					{
						type: 'tfhd-box',
						version: 0,
						trackId: 2,
						baseDataOffset: 1272,
						baseSampleDescriptionIndex: 0,
						defaultSampleDuration: 2940,
						defaultSampleSize: 21,
						defaultSampleFlags: 33554432,
					},
					{type: 'tfdt-box', version: 1, baseMediaDecodeTime: 0, offset: 1668},
					{
						type: 'trun-box',
						version: 0,
						sampleCount: 42,
						dataOffset: 10943,
						firstSampleFlags: null,
						samples: [
							{
								sampleDuration: 2940,
								sampleSize: 21,
								sampleFlags: null,
								sampleCompositionTimeOffset: null,
							},
							{
								sampleDuration: 1024,
								sampleSize: 6,
								sampleFlags: null,
								sampleCompositionTimeOffset: null,
							},
							{
								sampleDuration: 1024,
								sampleSize: 6,
								sampleFlags: null,
								sampleCompositionTimeOffset: null,
							},
							{
								sampleDuration: 1024,
								sampleSize: 6,
								sampleFlags: null,
								sampleCompositionTimeOffset: null,
							},
							{
								sampleDuration: 1024,
								sampleSize: 6,
								sampleFlags: null,
								sampleCompositionTimeOffset: null,
							},
							{
								sampleDuration: 1024,
								sampleSize: 6,
								sampleFlags: null,
								sampleCompositionTimeOffset: null,
							},
							{
								sampleDuration: 1024,
								sampleSize: 6,
								sampleFlags: null,
								sampleCompositionTimeOffset: null,
							},
							{
								sampleDuration: 1024,
								sampleSize: 6,
								sampleFlags: null,
								sampleCompositionTimeOffset: null,
							},
							{
								sampleDuration: 1024,
								sampleSize: 6,
								sampleFlags: null,
								sampleCompositionTimeOffset: null,
							},
							{
								sampleDuration: 1024,
								sampleSize: 6,
								sampleFlags: null,
								sampleCompositionTimeOffset: null,
							},
							{
								sampleDuration: 1024,
								sampleSize: 6,
								sampleFlags: null,
								sampleCompositionTimeOffset: null,
							},
							{
								sampleDuration: 1024,
								sampleSize: 6,
								sampleFlags: null,
								sampleCompositionTimeOffset: null,
							},
							{
								sampleDuration: 1024,
								sampleSize: 6,
								sampleFlags: null,
								sampleCompositionTimeOffset: null,
							},
							{
								sampleDuration: 1024,
								sampleSize: 6,
								sampleFlags: null,
								sampleCompositionTimeOffset: null,
							},
							{
								sampleDuration: 1024,
								sampleSize: 6,
								sampleFlags: null,
								sampleCompositionTimeOffset: null,
							},
							{
								sampleDuration: 1024,
								sampleSize: 6,
								sampleFlags: null,
								sampleCompositionTimeOffset: null,
							},
							{
								sampleDuration: 1024,
								sampleSize: 6,
								sampleFlags: null,
								sampleCompositionTimeOffset: null,
							},
							{
								sampleDuration: 1024,
								sampleSize: 6,
								sampleFlags: null,
								sampleCompositionTimeOffset: null,
							},
							{
								sampleDuration: 1024,
								sampleSize: 6,
								sampleFlags: null,
								sampleCompositionTimeOffset: null,
							},
							{
								sampleDuration: 1024,
								sampleSize: 6,
								sampleFlags: null,
								sampleCompositionTimeOffset: null,
							},
							{
								sampleDuration: 1024,
								sampleSize: 6,
								sampleFlags: null,
								sampleCompositionTimeOffset: null,
							},
							{
								sampleDuration: 1024,
								sampleSize: 6,
								sampleFlags: null,
								sampleCompositionTimeOffset: null,
							},
							{
								sampleDuration: 1024,
								sampleSize: 6,
								sampleFlags: null,
								sampleCompositionTimeOffset: null,
							},
							{
								sampleDuration: 1024,
								sampleSize: 6,
								sampleFlags: null,
								sampleCompositionTimeOffset: null,
							},
							{
								sampleDuration: 1024,
								sampleSize: 6,
								sampleFlags: null,
								sampleCompositionTimeOffset: null,
							},
							{
								sampleDuration: 1024,
								sampleSize: 6,
								sampleFlags: null,
								sampleCompositionTimeOffset: null,
							},
							{
								sampleDuration: 1024,
								sampleSize: 6,
								sampleFlags: null,
								sampleCompositionTimeOffset: null,
							},
							{
								sampleDuration: 1024,
								sampleSize: 6,
								sampleFlags: null,
								sampleCompositionTimeOffset: null,
							},
							{
								sampleDuration: 1024,
								sampleSize: 6,
								sampleFlags: null,
								sampleCompositionTimeOffset: null,
							},
							{
								sampleDuration: 1024,
								sampleSize: 6,
								sampleFlags: null,
								sampleCompositionTimeOffset: null,
							},
							{
								sampleDuration: 1024,
								sampleSize: 6,
								sampleFlags: null,
								sampleCompositionTimeOffset: null,
							},
							{
								sampleDuration: 1024,
								sampleSize: 6,
								sampleFlags: null,
								sampleCompositionTimeOffset: null,
							},
							{
								sampleDuration: 1024,
								sampleSize: 6,
								sampleFlags: null,
								sampleCompositionTimeOffset: null,
							},
							{
								sampleDuration: 1024,
								sampleSize: 6,
								sampleFlags: null,
								sampleCompositionTimeOffset: null,
							},
							{
								sampleDuration: 1024,
								sampleSize: 6,
								sampleFlags: null,
								sampleCompositionTimeOffset: null,
							},
							{
								sampleDuration: 1024,
								sampleSize: 6,
								sampleFlags: null,
								sampleCompositionTimeOffset: null,
							},
							{
								sampleDuration: 1024,
								sampleSize: 6,
								sampleFlags: null,
								sampleCompositionTimeOffset: null,
							},
							{
								sampleDuration: 1024,
								sampleSize: 6,
								sampleFlags: null,
								sampleCompositionTimeOffset: null,
							},
							{
								sampleDuration: 1024,
								sampleSize: 6,
								sampleFlags: null,
								sampleCompositionTimeOffset: null,
							},
							{
								sampleDuration: 1024,
								sampleSize: 6,
								sampleFlags: null,
								sampleCompositionTimeOffset: null,
							},
							{
								sampleDuration: 1024,
								sampleSize: 6,
								sampleFlags: null,
								sampleCompositionTimeOffset: null,
							},
							{
								sampleDuration: 1024,
								sampleSize: 6,
								sampleFlags: null,
								sampleCompositionTimeOffset: null,
							},
						],
					},
				],
				offset: 1624,
			},
		],
		offset: 1272,
	},
];
