export type SfxFinal = {
	slug: string;
	fileName: string;
	exportName: string;
	pageUrl: string;
	description: string;
	oldFileName?: string;
};

export const SFX_FINAL: SfxFinal[] = [
	{
		slug: 'fah',
		fileName: 'fah.wav',
		exportName: 'fah',
		oldFileName: 'faaah.wav',
		pageUrl: 'https://www.myinstants.com/en/instant/fahhhhhhhhhhhhhh-3525/',
		description: 'Fah meme sound effect',
	},
	{
		slug: 'spongebob-fail',
		fileName: 'spongebob-fail.wav',
		exportName: 'spongebobFail',
		pageUrl: 'https://www.myinstants.com/en/instant/spongebob-fail-11236/',
		description: 'SpongeBob fail sound effect',
	},
	{
		slug: 'omg-hell-nah',
		fileName: 'omg-hell-nah.wav',
		exportName: 'omgHellNah',
		pageUrl: 'https://www.myinstants.com/en/instant/oh-my-god-bro-oh-hell-nah-man-42939/',
		description: 'Oh my god bro hell nah sound effect',
	},
	{
		slug: 'price-is-right-fail',
		fileName: 'price-is-right-fail.wav',
		exportName: 'priceIsRightFail',
		oldFileName: 'fail-horn.wav',
		pageUrl: 'https://www.myinstants.com/en/instant/fail-horn/',
		description: 'Price Is Right fail horn sound effect',
	},
	{
		slug: 'romance-meme',
		fileName: 'romance-meme.wav',
		exportName: 'romanceMeme',
		oldFileName: 'romance.wav',
		pageUrl: 'https://www.myinstants.com/en/instant/romanceeeeeeeeeeeeee-29042/',
		description: 'Romance meme sound effect',
	},
	{
		slug: 'bone-crack',
		fileName: 'bone-crack.wav',
		exportName: 'boneCrack',
		pageUrl: 'https://www.myinstants.com/en/instant/bone-crack-23901/',
		description: 'Bone crack sound effect',
	},
	{
		slug: 'anime-wow',
		fileName: 'anime-wow.wav',
		exportName: 'animeWow',
		pageUrl: 'https://www.myinstants.com/en/instant/anime-wow/',
		description: 'Anime wow sound effect',
	},
	{
		slug: 'yippee',
		fileName: 'yippee.wav',
		exportName: 'yippee',
		oldFileName: 'yippieh.wav',
		pageUrl: 'https://www.myinstants.com/en/instant/yippeeeeeeeeeeeeee-34261/',
		description: 'Yippee sound effect',
	},
	{
		slug: 'loading-lag',
		fileName: 'loading-lag.wav',
		exportName: 'loadingLag',
		oldFileName: 'lagging.wav',
		pageUrl: 'https://www.myinstants.com/en/instant/lagging-loading-11339/',
		description: 'Loading lag sound effect',
	},
	{
		slug: 'wilhelm-scream',
		fileName: 'wilhelm-scream.wav',
		exportName: 'wilhelmScream',
		pageUrl: 'https://www.myinstants.com/en/instant/man-screaming-aaaah-32768/',
		description: 'Wilhelm scream sound effect',
	},
	{
		slug: 'mac-quack',
		fileName: 'mac-quack.wav',
		exportName: 'macQuack',
		oldFileName: 'quack.wav',
		pageUrl: 'https://www.myinstants.com/en/instant/mac-quack-83896/',
		description: 'Mac quack sound effect',
	},
	{
		slug: 'skedaddle',
		fileName: 'skedaddle.wav',
		exportName: 'skedaddle',
		pageUrl: 'https://www.myinstants.com/en/instant/skedaddle-78470/',
		description: 'Skedaddle sound effect',
	},
	{
		slug: 'snapchat-notification',
		fileName: 'snapchat-notification.wav',
		exportName: 'snapchatNotification',
		oldFileName: 'notification-snap.wav',
		pageUrl: 'https://www.myinstants.com/en/instant/notification-snap-43481/',
		description: 'Snapchat notification sound effect',
	},
	{
		slug: 'nelly-ahh',
		fileName: 'nelly-ahh.wav',
		exportName: 'nellyAhh',
		oldFileName: 'aah.wav',
		pageUrl: 'https://www.myinstants.com/en/instant/nelly-ahh-89172/',
		description: 'Nelly ahh sound effect',
	},
	{
		slug: 'sanctuary-guardian-what',
		fileName: 'sanctuary-guardian-what.wav',
		exportName: 'sanctuaryGuardianWhat',
		oldFileName: 'what.wav',
		pageUrl:
			'https://www.myinstants.com/en/instant/what-bottom-text-meme-sanctuary-guardian-s-24591/',
		description: 'Sanctuary Guardian what meme sound effect',
	},
	{
		slug: 'minecraft-hurt',
		fileName: 'minecraft-hurt.wav',
		exportName: 'minecraftHurt',
		oldFileName: 'hurt.wav',
		pageUrl: 'https://www.myinstants.com/en/instant/minecraft-hurt/',
		description: 'Minecraft hurt sound effect',
	},
	{
		slug: 'oh-my-god-vine',
		fileName: 'oh-my-god-vine.wav',
		exportName: 'ohMyGodVine',
		oldFileName: 'oh-ma-gaud.wav',
		pageUrl: 'https://www.myinstants.com/en/instant/oh-ma-gaud-vine-78004/',
		description: 'Oh my god vine sound effect',
	},
	{
		slug: 'illuminati-confirmed',
		fileName: 'illuminati-confirmed.wav',
		exportName: 'illuminatiConfirmed',
		oldFileName: 'illuminati.wav',
		pageUrl: 'https://www.myinstants.com/en/instant/illuminati-confirmed-meme-99730/',
		description: 'Illuminati confirmed sound effect',
	},
	{
		slug: 'dramatic-boomer',
		fileName: 'dramatic-boomer.wav',
		exportName: 'dramaticBoomer',
		pageUrl: 'https://www.myinstants.com/en/instant/dramatic-boomer-29428/',
		description: 'Dramatic boomer sound effect',
	},
	{
		slug: 'core-sound-effect',
		fileName: 'core-sound-effect.wav',
		exportName: 'coreSoundEffect',
		oldFileName: 'core-trigger.wav',
		pageUrl: 'https://www.myinstants.com/en/instant/core-sound-effect-57998/',
		description: 'Core sound effect',
	},
];

export const OLD_7054_FILES = [
	'faaah.wav',
	'x-files.wav',
	'fail-horn.wav',
	'romance.wav',
	'yippieh.wav',
	'lagging.wav',
	'quack.wav',
	'notification-snap.wav',
	'aah.wav',
	'what.wav',
	'hurt.wav',
	'oh-ma-gaud.wav',
	'illuminati.wav',
	'core-trigger.wav',
];
