// Execute with `bun packages/studio/scripts/generate-google-font-info.ts`

import {execSync} from 'child_process';
import {writeFileSync} from 'fs';
import path from 'path';
import {top250} from './top-250-google-fonts';

type BasicFontInfo = {
	importName: string;
	fontFamily: string;
	previewUrl: string;
};

const basicInfos: BasicFontInfo[] = [];

for (const font of top250) {
	const info = await font.load();
	const fontInfo = info.getInfo();
	const previewUrl = fontInfo.url.match(/family=(.*):/)?.[1];
	if (!previewUrl) {
		throw new Error(
			`Could not extract Google Fonts CSS family for ${font.family}`,
		);
	}

	basicInfos.push({
		importName: fontInfo.importName,
		fontFamily: fontInfo.fontFamily,
		previewUrl,
	});
}

const basicContent = [
	`// Auto-generated by packages/studio/scripts/generate-google-font-info.ts`,
	`export const GOOGLE_FONTS_LIST = ${JSON.stringify(basicInfos, null, 2)};`,
].join('\n');

writeFileSync(
	path.join(
		__dirname,
		'..',
		'src',
		'components',
		'Timeline',
		'google-fonts-list.ts',
	),
	basicContent,
);
execSync(
	`bunx oxfmt packages/studio/src/components/Timeline/google-fonts-list.ts --write`,
	{
		stdio: 'inherit',
	},
);
